# YOUR NAME OR TITLE OF YOUR SITE
name: Psicomage

# YOUR BRAND/PERSONAL TAGLINE
tagline: Reality is made with pixels

# YOUR/BRAND IMAGE URL
Image_URL: https://avatars.githubusercontent.com/u/113297103

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://previews.dropbox.com/p/thumb/AB2GmWh4Spp37Qm6x5-c_LpPn5Mji7DjNjNjckf1aGQ1XIhE0A474Bj_zfv3FsdSQAatLyMKJhm_rJccIPHVKNfNFFi-BwZHI_oynV6Oae6TZWZTA72YMmjYP4fPdqmnYI_pqMIcEIuyz8cIbt9XnkLIOkRmflmJ04WcVImuoNicaNLwK0WTlvII8pw5WpjbBtK4z5hdL-myzllv6UfaqDJQrBjXDnaArBo3rdyGOpYaqz9UOMe44YZKf7-juy98Q94Uy2aHKG8jXbhpOZ1rVwGZ0rnf88zDUx8osN0jHsZXXuw3CxkQ-69lP0dA2R2LYYzYfWNzmg5C67XWivkXLFfW7_lE2WVJEBSI0Azk9d9KT5fuw1OcwfLpc8Ez6E7zzhE/p.jpeg

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # CUSTOM LINK
    
  - Name: Opensea
    URL: https://opensea.io/Psicomage
    Icon-Class: fas fa-ship
    Color: '#2081E2'
    Text_Color: '#ffffff'
    
  - Name: Manifesto
    URL: https://psicomage-nfts-network.gitbook.io/psicomage-nfts-network-manifesto
    Icon-Class: fas fa-scroll
    Color: '#008000'
    Text_Color: '#ffffff'
    
  - Name: Showtime
    URL: https://showtime.xyz/@Psicomage
    Icon-Class: fas fa-star
    Color: '#000000'
    Text_Color: '#ffffff'

  # - Name: Links
  #   URL:
  #   Icon-Class: fas fa-link
  #   Color: '#d94869'
  #   Text_Color: '#ffffff'
  
  # DISCORD
  - Name: Discord
    URL: 'https://discord.gg'
    Username: ABGgURpk9w
    Icon-Class: fab fa-discord
    Color: '#5865F2'
    Text_Color: '#ffffff'
    
    # TWITTER
  - Name: Twitter
    URL: https://twitter.com
    Username: Psicomage1
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter
    
    # REDDIT
  - Name: Reddit
    URL: http://reddit.com/u
    Username: Psicomage
    Color: '#FF4500'
    Icon-Class: fab fa-reddit-alien
    
    # TELEGRAM
  - Name: Telegram
    URL: http://telegram.me
    Username: Psicomage
    Color: '#229ED9'
    Icon-Class: fab fa-telegram-plane

    # FACEBOOK
  - Name: Facebook
    URL: https://www.facebook.com
    Username: Psicomage
    Color: '#1877F2'
    Icon-Class: fab fa-facebook

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: psicomage1
    Color: '#833AB4'
    Icon-Class: fab fa-instagram

 #   # Cal.com
 # - Name: Cal.com
 #   URL:
 #   Username:
 #   Color: '#232323'
 #   Icon-Class: fa fa-calendar-check

    # CLUBHOUSE
  - #Name: Clubhouse
    #URL: https://www.clubhouse.com
    #Username: 
    #Color: '#f1c40f'
    #Icon-Class: fas fa-hand-paper -mt-0.5
    
    # LINKEDIN
  - #Name: LinkedIn
    #URL: https://www.linkedin.com/in
    #Username: harsh98trivedi
    #Color: '#2867B2'
    #Icon-Class: fab fa-linkedin-in

    # YOUTUBE
  - #Name: YouTube
    #URL: https://www.youtube.com/channel
    #Username: UCS3zvA_2r1iGT7MB3NVCGAw
    #Color: '#ff0000'
    #Icon-Class: fab fa-youtube

    # EMAIL
  - Name: Email
    URL: 'mailto:m.bagiante@mail.com'
    Icon-Class: fas fa-envelope
    Color: '#b7b814'
    Text_Color: '#ffffff'
    
    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: Psicomage
    Color: '#151013'
    Icon-Class: fab fa-github

    # TWITCH
  - #Name: Twitch
    #URL: 'https://twitch.tv'
    #Username: harsh98trivedi
    #Icon-Class: fab fa-twitch
    #Color: '#9147fe'
    #Text_Color: '#ffffff'

    # VIMEO
  - #Name: Vimeo
    #URL: 'https://vimeo.com'
    #Username: harshtrivedi
    #Icon-Class: fab fa-vimeo-v
    #Color: '#1ab7ea'
    #Text_Color: '#ffffff'

    # MESSENGER
  - #Name: Messenger
    #URL: https://m.me
    #Username: theharshtrivedi
    #Color: '#006AFF'
    #Icon-Class: fab fa-facebook-messenger

  #   # WHATSAPP
  # - Name: WhatsApp
  #   URL: https://wa.me
  #   Username: '+1123456789'
  #   Color: '#25d366'
  #   Icon-Class: fab fa-whatsapp

    # SNAPCHAT
  - #Name: Snapchat
    #URL: https://www.snapchat.com/add
    #Username: 'harsh98trivedi'
    #Color: '#FFFC00'
    #Text_Color: '#000000'
    #Icon-Class: fab fa-snapchat-ghost

    # STEAM
  - #Name: Steam
    #URL: https://steamcommunity.com/id
    #Username: 'harshtrivedi'
    #Color: '#66c0f4'
    #Text_Color: '#000000'
    #Icon-Class: fab fa-steam

    # PINTEREST
  - #Name: Pinterest
    #URL: https://pinterest.com
    #Username: 'harsh98trivedi'
    #Color: '#E60023'
    #Icon-Class: fab fa-pinterest

    # BEHANCE
  - #Name: Behance
    #URL: https://www.behance.net
    #Username: harsh98trivedi
    #Color: '#1769ff'
    #Icon-Class: fab fa-behance

  #   # DRIBBBLE
  # - Name: Dribbble
  #   URL: https://dribbble.com
  #   Username: 
  #   Color: '#ea4c89'
  #   Icon-Class: fab fa-dribbble

    # DEVIANTART
  - #Name: DeviantArt
    #URL: https://www.deviantart.com
    #Username: harshtrivedi
    #Icon-Class: fab fa-deviantart
    #Color: '#05CC46'
    #Text_Color: '#ffffff'

    # FIGMA
  - #Name: Figma
    #URL: https://www.figma.com
    #Username: '@harshtrivedi'
    #Icon-Class: fab fa-figma
    #Color: '#ff2865'
    #Text_Color: '#ffffff'

    # SPOTIFY
  - #Name: Spotify
    #URL: http://open.spotify.com/user
    #Username: 314ihryk3edvtusti6il3oy3x5da
    #Color: '#1DB954'
    #Icon-Class: fab fa-spotify

    # SOUNDCLOUD
  - #Name: SoundCloud
    #URL: https://www.soundcloud.com
    #Username: harsh98trivedi
    #Color: '#FE5000'
    #Icon-Class: fab fa-soundcloud

  #   # TIKTOK
  # - Name: TikTok
  #   URL: https://www.tiktok.com
  #   Username: 
  #   Color: '#FE2C55'
  #   Icon-Class: fab fa-tiktok

      # MEDIUM
  # - Name: Medium
  #   URL: 'https://medium.com'
  #   Username: '@harsh98trivedi'
  #   Icon-Class: fab fa-medium-m
  #   Color: '#00ab6c'
  #   Text_Color: '#ffffff'

      # DEV.TO
  # - Name: Dev.to
  #   URL: 'https://dev.to'
  #   Username:
  #   Icon-Class: fab fa-dev
  #   Color: '#ffffff'
  #   Text_Color: '#000000'

      # TUMBLR
  # - Name: Tumblr
  #   URL: https://www.tumblr.com
  #   Username: 
  #   Color: '#35465c'
  #   Icon-Class: fab fa-tumblr

  # BUY ME A COFFEE
  # - Name: BuyMeACoffee
  #   URL: 'https://buymeacoffee.com'
  #   Username:
  #   Icon-Class: fas fa-mug-hot
  #   Color: '#FFDD00'
  #   Text_Color: '#000000'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'Yes'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
